{{- if eq .Values.collection.mode "standalone" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-api-bridge.collectorServiceAccountName" . }}
  labels:
    {{- include "prometheus-api-bridge.collectorLabels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
